@baseURL = http://localhost:8001
# @baseURL = https://parked-car-owner-dev-api.onrender.com

###
GET {{baseURL}}


###
POST {{baseURL}}/register
Content-Type: application/json

{
    "name": "owner2",
    "email": "owner2",
    "phone": "1234567890",
    "password": "1234"
}

###
# @name login
POST {{baseURL}}/auth/login
Content-Type: application/json

{
    "email": "user1@test.com",
    "password": "123456"
}

###

@access_token = {{login.response.body.token}}
@refresh_token = {{login.response.body.refreshToken}} 

###
POST {{baseURL}}/auth/refresh
Content-Type: application/json

{
    "refreshToken": "{{refresh_token}}"
}

###
POST {{baseURL}}/auth/logout
Content-Type: application/json

{
    "refreshToken": "{{refresh_token}}"
}

###
GET {{baseURL}}/protected 
Authorization: Bearer {{access_token}}

###
POST {{baseURL}}/space/add
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "width": 10,
    "length": 10,
    "height": 10,
    "base_fare": 1000,
    "security_measures": "securityMeasures",
    "status": "status",
    "auto_approve": true,
    "address": "address",
    "city": "city",
    "latitude": 10,
    "longitude": 10
}

###
POST {{baseURL}}/space/update
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "width": 10,
    "length": 10,
    "height": 10,
    "base_fare": 100000,
    "security_measures": "securityMeasures",
    "status": "status",
    "auto_approve": true,
    "address": "address",
    "city": "city",
    "latitude": 10,
    "longitude": 10,
    "space_id": 36
}

###



###
GET {{baseURL}}/space/getMySpaces
Authorization: Bearer {{access_token}}
###
POST {{baseURL}}/space/changeSpaceStatus
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "spaceId": 36,
    "status": "disabled"
}

###
GET {{baseURL}}/space/getDisabledSpaces
Authorization: Bearer {{access_token}}

###
GET {{baseURL}}/space/getActiveSpaces
Authorization: Bearer {{access_token}}

###
GET {{baseURL}}/space/getRequestedSpaces
Authorization: Bearer {{access_token}}

###
GET {{baseURL}}/space/getSpace
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "space_id": 39
}

###
POST {{baseURL}}/booking/user
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "status": "requested"
}

###
POST {{baseURL}}/booking/space_bookings
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "space_id": 39,
    "status": "requested"
}

###
POST {{baseURL}}/booking/details
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "booking_id": 10
}